image: ruby:3.3

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
    - gem install bundler -v 2.5.23
    - bundle config set --local path 'vendor/bundle'
    - bundle install
  artifacts:
    paths:
      - vendor/bundle

test:
  stage: test
  script:
    - export RACK_ENV=test
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - ruby app.rb & 
    - sleep 5
    - bundle exec ruby spec/app_spec.rb
