# Stage 1: Build
FROM maven:3.8.1-openjdk-17 AS build

# Set working directory
WORKDIR /app

# Copy the pom.xml file and resolve dependencies
COPY pom.xml ./
RUN mvn dependency:go-offline -B

# Copy the source code and build the project
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jre

# Set the working directory in the runtime image
WORKDIR /app

# Copy the packaged JAR file from the build stage
COPY --from=build /app/target/comma-counter-0.0.1-SNAPSHOT.jar app.jar

# Install curl
RUN apt-get update && apt-get install -y curl

# Expose port 8080 to the host
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
